### ISSUE TITLE
PGBlitz /w Encryption redeploy created new encrypt folder

### ISSUE THREAD

**Issue by DomGrieco** [PGBlitz/PGClone#10]
This issue lead to a slight heart attack but figured out whats going on.

When redeploying mounts with new project keys/emails it created a new encrypt folder, when it shouldn't (because it exist). What this seemed to do is made the current encrypt folder disappear on TDRIVE for about 30 mins or so, leading to the belief everything was lost. Some time later two encrypt folders showed up in TDRIVE. Fixed issue by merging the two.

Currently on PG version 8.3.13. Issue happened on February 6th, 2019 @ 9:42 AM AST (for finding PGCLONE versions).

![chrome_2019-02-06_11-01-22](https://user-images.githubusercontent.com/6556434/52351759-c205ba80-2a01-11e9-8a87-bd6b23753b84.png)

**Comment by Admin9705** [comment]
got it! working on 8.6! what i'll do is have it detect if that folder is there and to not regenerate it. working on 8.6; improved pgclone interface!

**Comment by Admin9705** [comment]
ok just an update going to close this, but now the feature prevents this from occuring; it only creates the folder if it is missing. 8.6 is not fully out yet though; but you get the idea.
