### ISSUE TITLE
Type f command 

### ISSUE THREAD

**Issue by MrDoobPG** [PGBlitz/PGClone#35]
https://github.com/PGBlitz/PGClone/blob/6f44e2f9087ca1e7d7d0159fcafc83140f797d60/scripts/cloneclean.sh#L23

This will remove all files && 

Self the excluded folder will ignored !!

We must find a better command for this !!

**Comment by robertbaker** [comment]
fixed. clone clean is now more explicit and only deletes empties and files less than 3gb from the nzb folders. torrents and any other folder is left alone (except deleting empties)
