### ISSUE TITLE
"Unlimited" Service Account Creation

### ISSUE THREAD

**Issue by DomGrieco** [PGBlitz/PGClone#9]
If you accidentally double tap enter and skip the part of the script that ask how many keys would you like to enter, it seems to start creating keys. I let it get up to 80 keys before I force stopped the script.

Recommend adding a conditional check for valid input so that if the user doesn't enter in anything it will display a failed message and ask for input again.

**Comment by Admin9705** [comment]
ya i heard, i'll check into it :D

**Comment by Admin9705** [comment]
working on 8.6 to prevent this; just fyi!
